# Generated by Django 3.2.9 on 2021-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211130_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
