# Generated by Django 3.2.9 on 2021-12-03 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dashboarduser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('spotify', 'Spotify'), ('google', 'Google'), ('github', 'Github')], max_length=7)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.dashboarduser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('params', models.JSONField()),
                ('service', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='api.dashboardservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
