# Generated by Django 3.2.9 on 2021-12-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_provider_dashboardservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardservice',
            name='name',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('google', 'Google'), ('github', 'Github'), ('connection_less', 'Connection Less')], max_length=15),
        ),
    ]
