# Generated by Django 3.2.9 on 2021-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dashboardservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='params',
            field=models.JSONField(blank=True),
        ),
    ]
