# Generated by Django 3.2.9 on 2021-12-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dashboardwidget_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedDashboardUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.dashboarduser',),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
