# Generated by Django 3.2.9 on 2021-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211211_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardservice',
            name='token',
            field=models.JSONField(default=None, null=True),
        ),
    ]
