# Generated by Django 3.2.9 on 2021-12-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dashboardservice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardservice',
            name='token',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
