# Generated by Django 3.2.9 on 2021-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_dashboardservice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
