# Generated by Django 3.2.9 on 2021-12-14 19:21

from django.db import migrations
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dashboarduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardservice',
            name='token',
            field=django_cryptography.fields.PickledField(blank=True, default=None, null=True),
        ),
    ]
