# Generated by Django 3.2.9 on 2021-12-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dashboarduser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
